#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
/** @var Application $app */
$app = require_once __DIR__.'/bootstrap/app.php';

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

foreach ($kernel->all() as $command) {
	if (method_exists($command, 'setLaravel') && method_exists($command, 'getLaravel') && !$command->getLaravel()) {
		$command->setLaravel($app);
	}
}

$status = $app->handleCommand(new ArgvInput);

exit($status);
